PUBLISH_STATUS_DRAFT = "draft"
PUBLISH_STATUS_PUBLISHED = "published"
PUBLISH_STATUS_CHOICES = [
    (PUBLISH_STATUS_DRAFT, "Draft"),
    (PUBLISH_STATUS_PUBLISHED, "Published"),
]

EMAIL_NOTIFICATION_TYPE_ORDER = "order"
EMAIL_NOTIFICATION_TYPE_INQUIRY = "inquiry"
EMAIL_NOTIFICATION_TYPE_CHOICES = [
    (EMAIL_NOTIFICATION_TYPE_ORDER, "Order"),
    (EMAIL_NOTIFICATION_TYPE_INQUIRY, "Inquiry"),
]

CHARACTERISTIC_TYPE_TEXT = "text"
CHARACTERISTIC_TYPE_NUMBER = "number"
CHARACTERISTIC_TYPE_BOOLEAN = "boolean"
CHARACTERISTIC_TYPE_CHOICES = [
    (CHARACTERISTIC_TYPE_TEXT, "Text"),
    (CHARACTERISTIC_TYPE_NUMBER, "Number"),
    (CHARACTERISTIC_TYPE_BOOLEAN, "Boolean"),
]
