# Generated by Django 5.0.1 on 2026-04-24 14:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_inquiry_phone_alter_inquiry_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='new', max_length=50)),
                ('total_items', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'public_orders',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PublicOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.publicorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_order_items', to='shop.product')),
            ],
            options={
                'db_table': 'public_order_items',
                'ordering': ['id'],
            },
        ),
    ]
