# Generated by Django 5.0.1 on 2026-04-24 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_publicorder_publicorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.IntegerField()),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'serts',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productmedia',
            name='media_kind',
            field=models.CharField(default='image', max_length=50),
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.IntegerField()),
                ('sort_order', models.IntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='shop.news')),
            ],
            options={
                'db_table': 'news_attachments',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.IntegerField()),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='shop.product')),
            ],
            options={
                'db_table': 'product_certificates',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
