# Generated by Django 5.0.1 on 2026-04-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_sert_productmedia_media_kind_newsattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_path', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(max_length=255)),
                ('file_kind', models.CharField(default='image', max_length=50)),
                ('size_bytes', models.IntegerField()),
                ('sort_order', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='shop.product')),
            ],
            options={
                'db_table': 'product_gallery_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
