# Generated by Django 5.0.1 on 2026-04-27 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_productgalleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Наши контакты', max_length=255)),
                ('address', models.TextField()),
                ('schedule', models.TextField()),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact info',
                'verbose_name_plural': 'Contact info',
                'db_table': 'contact_info',
                'ordering': ['-is_active', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HtmlContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Main HTML content', max_length=255)),
                ('html_first', models.TextField()),
                ('html_second', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'html_content',
                'ordering': ['-is_active', '-updated_at', '-id'],
            },
        ),
    ]
