# Generated by Django 5.0.1 on 2026-04-28 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_contactinfo_htmlcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order email recipient',
                'verbose_name_plural': 'Order email recipients',
                'db_table': 'order_email_recipients',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='OrderEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Order email settings', max_length=255)),
                ('subject', models.CharField(default='Новый заказ с сайта', max_length=255)),
                ('intro_html', models.TextField(blank=True, null=True)),
                ('footer_html', models.TextField(blank=True, null=True)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order email settings',
                'verbose_name_plural': 'Order email settings',
                'db_table': 'order_email_settings',
                'ordering': ['-is_active', '-updated_at', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='savedfilter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='savedfilter',
            name='group',
        ),
        migrations.AddField(
            model_name='product',
            name='assortment_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='SavedFilter',
        ),
    ]
