# Generated by Django 5.0.1 on 2026-04-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orderemailrecipient_orderemailsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
