# Generated by Django 5.0.1 on 2026-04-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_legacy_user_and_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='title',
            field=models.CharField(default='РќР°С€Рё РєРѕРЅС‚Р°РєС‚С‹', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderemailsettings',
            name='subject',
            field=models.CharField(default='РќРѕРІС‹Р№ Р·Р°РєР°Р· СЃ СЃР°Р№С‚Р°', max_length=255),
        ),
    ]
