# Generated by Django 5.0.1 on 2026-04-30 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_publish_workflow(apps, schema_editor):
    now = django.utils.timezone.now()
    News = apps.get_model('shop', 'News')
    Slider = apps.get_model('shop', 'Slider')
    Sert = apps.get_model('shop', 'Sert')
    HtmlContent = apps.get_model('shop', 'HtmlContent')
    ContactInfo = apps.get_model('shop', 'ContactInfo')
    OrderEmailSettings = apps.get_model('shop', 'OrderEmailSettings')

    News.objects.filter(is_published=True).update(status='published')
    News.objects.filter(is_published=False).update(status='draft')
    News.objects.filter(is_published=True, published_at__isnull=True).update(published_at=now)

    Slider.objects.filter(is_active=True).update(status='published')
    Slider.objects.filter(is_active=False).update(status='draft')

    Sert.objects.filter(is_active=True).update(status='published')
    Sert.objects.filter(is_active=False).update(status='draft')

    for model in (HtmlContent, ContactInfo, OrderEmailSettings):
        active_items = list(model.objects.filter(is_active=True).order_by('-updated_at', '-id'))
        if active_items:
            keep_id = active_items[0].pk
            model.objects.filter(pk=keep_id).update(status='published')
            model.objects.exclude(pk=keep_id).update(status='draft')
        else:
            model.objects.all().update(status='draft')


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_medialibrary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Contact info', 'verbose_name_plural': 'Contact info'},
        ),
        migrations.AlterModelOptions(
            name='htmlcontent',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', '-updated_at', '-id'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='orderemailsettings',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Order email settings', 'verbose_name_plural': 'Order email settings'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='htmlcontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='htmlcontent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderemailsettings',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='orderemailsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sert',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='sert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sert',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='slider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='title',
            field=models.CharField(default='Наши контакты', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderemailsettings',
            name='subject',
            field=models.CharField(default='Новый заказ с сайта', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='search_tsv',
            field=models.TextField(blank=True, null=True, verbose_name='Search synonyms'),
        ),
        migrations.RunPython(migrate_publish_workflow, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='contactinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='htmlcontent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='orderemailsettings',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sert',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='is_active',
        ),
    ]
