# Generated by Django 5.0.1 on 2026-06-05 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_orderemailsettings_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Общая галерея',
                'verbose_name_plural': 'Общие галереи',
                'db_table': 'shared_product_galleries',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['sort_order', 'name', 'id'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Контактная информация', 'verbose_name_plural': 'Контактная информация'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа товаров', 'verbose_name_plural': 'Группы товаров'},
        ),
        migrations.AlterModelOptions(
            name='htmlcontent',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Реквизиты компании', 'verbose_name_plural': 'Реквизиты компании'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='medialibrary',
            options={'verbose_name': 'Библиотека медиа', 'verbose_name_plural': 'Библиотека медиа'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', '-updated_at', '-id'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newsattachment',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Файл новости', 'verbose_name_plural': 'Файлы новостей'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productcertificate',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Сертификат товара', 'verbose_name_plural': 'Сертификаты товаров'},
        ),
        migrations.AlterModelOptions(
            name='productcharacteristic',
            options={'verbose_name': 'Значение характеристики товара', 'verbose_name_plural': 'Значения характеристик товаров'},
        ),
        migrations.AlterModelOptions(
            name='productgalleryitem',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Элемент галереи товара', 'verbose_name_plural': 'Галерея товаров'},
        ),
        migrations.AlterModelOptions(
            name='sert',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Общий сертификат', 'verbose_name_plural': 'Общие сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AlterField(
            model_name='htmlcontent',
            name='title',
            field=models.CharField(default='Реквизиты компании', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='shared_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.sharedproductgallery'),
        ),
        migrations.CreateModel(
            name='SharedProductGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_path', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(max_length=255)),
                ('file_kind', models.CharField(default='image', max_length=50)),
                ('size_bytes', models.IntegerField()),
                ('sort_order', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.sharedproductgallery')),
            ],
            options={
                'verbose_name': 'Элемент общей галереи',
                'verbose_name_plural': 'Элементы общей галереи',
                'db_table': 'shared_product_gallery_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
