# Generated by Django 5.0.1 on 2026-06-07 12:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_sharedproductgallery_alter_agent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='import_jobs/source/%Y/%m/%d')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('processing', 'Обрабатывается'), ('succeeded', 'Завершён'), ('failed', 'Ошибка')], default='queued', max_length=32)),
                ('queue_name', models.CharField(default='catalog_import_jobs', max_length=255)),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('fatal_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Импорт каталога',
                'verbose_name_plural': 'Импорт каталога',
                'db_table': 'catalog_import_jobs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
